version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /external/v2ray-plugin
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /msi-installer
    schedule:
      interval: weekly
