//! SPIKE (#868) — throwaway experiment, NOT for merge.
//!
//! One question: **can Hole make its own resolver the macOS default without
//! writing to any of the user's network services, and can it be removed
//! cleanly?**
//!
//! The candidate mechanism publishes a DNS dictionary at a SYNTHETIC dynamic
//! store key — `State:/Network/Service/<a UUID we invent>/DNS`, for a service
//! that does not exist — carrying `SupplementalMatchDomains = [""]` (an empty
//! match domain matches every query) and a `SearchOrder` below the 200000
//! default. Nothing of the user's is read or captured, so teardown is removing
//! that one key and there is nothing to restore.
//!
//! The known risk is openconnect's `vpnc-script`, whose synthetic-service
//! approach stopped sufficing around Mojave. The argument that this is a
//! different mechanism (it supplied an IPv4 entity and fought primary-service
//! election; this rides the supplemental path) is not provable from sources.
//! It is provable on hardware, and CI has macOS.
//!
//! ## How to read the result
//!
//! The test prints a `SPIKE VERDICT` block and full `scutil --dns` /
//! `netstat -rn` / `route -n get` dumps on every path. The three outcomes are
//! distinct on purpose:
//!
//! - `CONTROL FAILED` — our own datagram to the test resolver never surfaced on
//!   the utun. Routing or frame handling is wrong. Says NOTHING about the
//!   mechanism; it is ordinary debugging.
//! - `MECHANISM: NO` — control passed, the key was accepted, and the OS's own
//!   resolver never sent the probe query into the utun. The mechanism does not
//!   suffice on this macOS.
//! - `MECHANISM: YES` — control passed AND a DNS query for our nonce name,
//!   generated by `getaddrinfo(3)` (not by any hand-rolled DNS client), arrived
//!   on the utun addressed to the synthetic resolver.
//!
//! Without the control, "my test is broken" and "the mechanism does not work"
//! are indistinguishable. The control runs FIRST, and its failure aborts before
//! the mechanism is ever judged.
//!
//! Runs on the privileged macOS lane (`SKULD_LABELS=tun`, under `sudo` — see
//! ci.yaml's "Test (TUN, macOS — root for pfctl)" step): opening a utun,
//! installing a route and writing the dynamic store all need root.
//!
//! While the key is published, `SupplementalMatchDomains = [""]` points the
//! WHOLE MACHINE's DNS at a black hole for the duration — that is the mechanism
//! working, not a side effect to design around. The window is bounded by the
//! test body, and every other test on this lane connects to IP literals, so
//! nothing else on the runner depends on name resolution meanwhile.
//!
//! COUPLED NAMES: `.config/nextest.toml` matches this test by the
//! `macos_dns_spike_` name prefix, for both the `global-net-state` group (it
//! mutates host-global routing + DNS state, so it must not run beside the pf
//! lockdown tests, whose `block drop out quick all` would swallow the probe)
//! and for `success-output = "immediate"` (a spike whose deliverable is the log
//! is useless if nextest hides the log on a pass).

hole_test_observability::register!();

fn main() {
    skuld::run_all();
}

#[skuld::label]
const TUN: skuld::Label;

#[cfg(target_os = "macos")]
mod spike {
    use std::ffi::CString;
    use std::io::Write;
    use std::net::{Ipv4Addr, ToSocketAddrs, UdpSocket};
    use std::process::{Command, Stdio};
    use std::time::{Duration, Instant};

    use core_foundation::array::CFArray;
    use core_foundation::base::{CFType, TCFType};
    use core_foundation::dictionary::CFDictionary;
    use core_foundation::number::CFNumber;
    use core_foundation::string::CFString;
    use system_configuration::dynamic_store::{SCDynamicStore, SCDynamicStoreBuilder};
    use system_configuration::sys::schema_definitions::{
        kSCPropNetDNSSearchOrder, kSCPropNetDNSServerAddresses, kSCPropNetDNSSupplementalMatchDomains,
    };

    /// TEST-NET-1 (RFC 5737). Deliberately not a real public resolver: a runner
    /// whose own DNS already pointed at 1.1.1.1 would make the assertion pass by
    /// coincidence. Nothing can reach 192.0.2.53 by accident.
    pub const RESOLVER: Ipv4Addr = Ipv4Addr::new(192, 0, 2, 53);
    pub const RESOLVER_NET: &str = "192.0.2.0/24";
    /// Point-to-point addressing for the spike's utun. Never advertised
    /// anywhere; only the RESOLVER_NET route points into this interface.
    pub const TUN_LOCAL: Ipv4Addr = Ipv4Addr::new(10, 255, 254, 1);
    pub const TUN_PEER: Ipv4Addr = Ipv4Addr::new(10, 255, 254, 2);

    /// The UUID we invent. It names no service that exists; the point of the
    /// mechanism is that configd merges it anyway, as a supplemental resolver.
    /// Hard-coded rather than random so a stranded key is greppable by hand.
    const SYNTHETIC_SERVICE: &str = "A3F1C0DE-8B52-4D7E-9F14-008680086800";
    /// Below configd's 200000 default, matching Tailscale's choice.
    const SEARCH_ORDER: i32 = 100_000;

    /// configd posts this when the merged DNS configuration changes. Registering
    /// for it BEFORE mutating the store makes the wait race-free: any post that
    /// our write causes is queued on the fd before we block.
    const DNS_CONFIG_NOTIFY_KEY: &str = "com.apple.system.SystemConfiguration.dns_configuration";

    pub fn key() -> String {
        format!("State:/Network/Service/{SYNTHETIC_SERVICE}/DNS")
    }

    // Shelling out ----------------------------------------------------------------------------------------------------

    pub fn run(cmd: &str, args: &[&str]) -> (bool, String) {
        match Command::new(cmd).args(args).output() {
            Ok(out) => (
                out.status.success(),
                format!(
                    "$ {cmd} {}\n[{}]\n{}{}",
                    args.join(" "),
                    out.status,
                    String::from_utf8_lossy(&out.stdout),
                    String::from_utf8_lossy(&out.stderr),
                ),
            ),
            Err(e) => (false, format!("$ {cmd} {}\n[spawn failed] {e}", args.join(" "))),
        }
    }

    /// `scutil`'s interactive `show`, so the applied dictionary is in the log
    /// verbatim — including whether the empty-string match domain survived.
    pub fn scutil_show(store_key: &str) -> String {
        let child = Command::new("scutil")
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn();
        let Ok(mut child) = child else {
            return format!("scutil spawn failed: {:?}", child.err());
        };
        if let Some(mut stdin) = child.stdin.take() {
            let _ = stdin.write_all(format!("show {store_key}\nquit\n").as_bytes());
        }
        match child.wait_with_output() {
            Ok(out) => format!(
                "{}{}",
                String::from_utf8_lossy(&out.stdout),
                String::from_utf8_lossy(&out.stderr)
            ),
            Err(e) => format!("scutil wait failed: {e}"),
        }
    }

    pub fn scutil_dns() -> String {
        run("scutil", &["--dns"]).1
    }

    /// Every `nameserver[N] : ADDR` line in `scutil --dns`, sorted and deduped —
    /// the structural shape of "which resolvers does this machine use", stable
    /// enough to compare before against after.
    pub fn nameservers(scutil_dns_output: &str) -> Vec<String> {
        let mut out: Vec<String> = scutil_dns_output
            .lines()
            .map(str::trim)
            .filter(|l| l.starts_with("nameserver["))
            .map(str::to_owned)
            .collect();
        out.sort();
        out.dedup();
        out
    }

    pub fn diagnostics(phase: &str, tun_name: &str) {
        println!("\n========== DIAGNOSTICS [{phase}] ==========");
        println!("{}", scutil_dns());
        println!("{}", run("route", &["-n", "get", &RESOLVER.to_string()]).1);
        println!("{}", run("netstat", &["-rn", "-f", "inet"]).1);
        println!("{}", run("ifconfig", &[tun_name]).1);
        println!("--- scutil show {} ---\n{}", key(), scutil_show(&key()));
        println!("========== END DIAGNOSTICS [{phase}] ==========\n");
    }

    // configd change notification -------------------------------------------------------------------------------------

    extern "C" {
        fn notify_register_file_descriptor(
            name: *const libc::c_char,
            notify_fd: *mut libc::c_int,
            flags: libc::c_int,
            out_token: *mut libc::c_int,
        ) -> u32;
        fn notify_cancel(token: libc::c_int) -> u32;
    }

    pub struct DnsConfigNotify {
        fd: libc::c_int,
        token: libc::c_int,
    }

    impl DnsConfigNotify {
        pub fn register() -> Option<Self> {
            let name = CString::new(DNS_CONFIG_NOTIFY_KEY).expect("notify key has no interior NUL");
            let mut fd: libc::c_int = -1;
            let mut token: libc::c_int = 0;
            // SAFETY: `name` is a valid NUL-terminated string that outlives the
            // call; `fd`/`token` are live out-params.
            let status = unsafe { notify_register_file_descriptor(name.as_ptr(), &mut fd, 0, &mut token) };
            (status == 0).then_some(Self { fd, token })
        }

        /// Block until configd posts a DNS-configuration change, or `deadline`
        /// passes. Returns whether a post was consumed.
        ///
        /// `deadline` is a failure bound on an EXTERNAL event (configd deciding
        /// to republish), surfaced to a human in the verdict — not a sleep
        /// standing in for synchronisation. The rendezvous itself is the
        /// kernel-delivered notification.
        fn wait(&self, deadline: Instant) -> bool {
            loop {
                let remaining = deadline.saturating_duration_since(Instant::now());
                if remaining.is_zero() {
                    return false;
                }
                let millis = libc::c_int::try_from(remaining.as_millis().max(1)).unwrap_or(libc::c_int::MAX);
                let mut pfd = libc::pollfd {
                    fd: self.fd,
                    events: libc::POLLIN,
                    revents: 0,
                };
                // SAFETY: single live pollfd, count matches.
                match unsafe { libc::poll(&mut pfd, 1, millis) } {
                    -1 if std::io::Error::last_os_error().kind() == std::io::ErrorKind::Interrupted => continue,
                    -1 => return false,
                    0 => return false,
                    _ => {
                        let mut token_be = [0u8; 4];
                        // SAFETY: reading 4 bytes into a 4-byte buffer.
                        let n = unsafe { libc::read(self.fd, token_be.as_mut_ptr().cast(), 4) };
                        return n == 4;
                    }
                }
            }
        }

        /// Block until `scutil --dns` mentioning `needle` equals `want`, driven
        /// by configd's own change posts. Checks the predicate first so an
        /// already-satisfied state needs no event at all.
        pub fn settle(&self, deadline: Instant, needle: &str, want: bool) -> bool {
            loop {
                if scutil_dns().contains(needle) == want {
                    return true;
                }
                if !self.wait(deadline) {
                    return scutil_dns().contains(needle) == want;
                }
            }
        }
    }

    impl Drop for DnsConfigNotify {
        fn drop(&mut self) {
            // `notify_cancel` closes the descriptor it handed us.
            // SAFETY: token was produced by a successful registration.
            unsafe { notify_cancel(self.token) };
        }
    }

    // Packet inspection -----------------------------------------------------------------------------------------------

    /// A macOS utun fd frames every packet with a 4-byte address family. `tun`'s
    /// reader strips it when `packet_information` is on (the macOS default), so
    /// a frame normally starts at the IP header. Tolerate both, so a
    /// PI-handling mistake reads as a parse rather than as "no packet arrived".
    fn ip_payload(frame: &[u8]) -> Option<&[u8]> {
        if frame.first().is_some_and(|b| b >> 4 == 4) {
            return Some(frame);
        }
        if frame.len() > 4 && frame[4] >> 4 == 4 {
            return Some(&frame[4..]);
        }
        None
    }

    pub struct Udp<'a> {
        pub src: Ipv4Addr,
        pub dst: Ipv4Addr,
        pub sport: u16,
        pub dport: u16,
        pub payload: &'a [u8],
    }

    fn parse_udp_v4(frame: &[u8]) -> Option<Udp<'_>> {
        let ip = ip_payload(frame)?;
        if ip.len() < 20 {
            return None;
        }
        let ihl = ((ip[0] & 0x0f) as usize) * 4;
        if ihl < 20 || ip.len() < ihl + 8 || ip[9] != 17 {
            return None;
        }
        let udp = &ip[ihl..];
        Some(Udp {
            src: Ipv4Addr::new(ip[12], ip[13], ip[14], ip[15]),
            dst: Ipv4Addr::new(ip[16], ip[17], ip[18], ip[19]),
            sport: u16::from_be_bytes([udp[0], udp[1]]),
            dport: u16::from_be_bytes([udp[2], udp[3]]),
            payload: &udp[8..],
        })
    }

    /// Read frames off the utun until one satisfies `want` or `deadline` passes.
    /// Every frame seen is appended to `seen` so a miss is diagnosable rather
    /// than merely negative.
    ///
    /// `deadline` bounds an EXTERNAL event (the OS resolver choosing to emit a
    /// query); it is the failure signal reported to a human, not a sync sleep.
    pub fn capture(
        dev: &tun::Device,
        deadline: Instant,
        seen: &mut Vec<String>,
        want: impl Fn(&Udp<'_>) -> bool,
    ) -> bool {
        let mut buf = vec![0u8; 4096];
        loop {
            let remaining = deadline.saturating_duration_since(Instant::now());
            if remaining.is_zero() {
                return false;
            }
            match dev.recv_timeout(&mut buf[..], remaining) {
                Ok(n) => match parse_udp_v4(&buf[..n]) {
                    Some(udp) => {
                        seen.push(format!(
                            "UDP {}:{} -> {}:{} payload={} bytes {:02x?}",
                            udp.src,
                            udp.sport,
                            udp.dst,
                            udp.dport,
                            udp.payload.len(),
                            &udp.payload[..udp.payload.len().min(48)],
                        ));
                        if want(&udp) {
                            return true;
                        }
                    }
                    None => seen.push(format!("non-UDPv4 frame, {n} bytes: {:02x?}", &buf[..n.min(16)])),
                },
                Err(e) if e.kind() == std::io::ErrorKind::TimedOut => return false,
                Err(e) if e.kind() == std::io::ErrorKind::Interrupted => continue,
                Err(e) => {
                    seen.push(format!("utun recv error: {e}"));
                    return false;
                }
            }
        }
    }

    // The mechanism ---------------------------------------------------------------------------------------------------

    pub fn store() -> SCDynamicStore {
        SCDynamicStoreBuilder::new("hole-868-spike")
            .build()
            .expect("open an SCDynamicStore session")
    }

    /// `{ ServerAddresses: [RESOLVER], SupplementalMatchDomains: [""],
    /// SearchOrder: 100000 }` — the whole mechanism, in one dictionary.
    fn dns_dictionary() -> CFDictionary {
        // SAFETY: schema constants are immortal CFStringRefs owned by the framework.
        let (k_servers, k_domains, k_order) = unsafe {
            (
                CFString::wrap_under_get_rule(kSCPropNetDNSServerAddresses),
                CFString::wrap_under_get_rule(kSCPropNetDNSSupplementalMatchDomains),
                CFString::wrap_under_get_rule(kSCPropNetDNSSearchOrder),
            )
        };
        let servers = CFArray::from_CFTypes(&[CFString::new(&RESOLVER.to_string())]);
        // The single empty string: matches every query.
        let domains = CFArray::from_CFTypes(&[CFString::new("")]);
        let pairs: [(CFString, CFType); 3] = [
            (k_servers, servers.as_CFType()),
            (k_domains, domains.as_CFType()),
            (k_order, CFNumber::from(SEARCH_ORDER).as_CFType()),
        ];
        let typed = CFDictionary::from_CFType_pairs(&pairs);
        // SAFETY: re-viewing the same dictionary through the untyped alias the
        // property-list API takes; the get-rule retain balances the wrapper.
        unsafe { CFDictionary::wrap_under_get_rule(typed.as_concrete_TypeRef()) }
    }

    pub fn publish(store: &SCDynamicStore) -> bool {
        store.set(CFString::new(&key()), dns_dictionary())
    }

    pub fn withdraw(store: &SCDynamicStore) -> bool {
        store.remove(CFString::new(&key()))
    }

    pub fn key_present(store: &SCDynamicStore) -> bool {
        store.get(CFString::new(&key())).is_some()
    }

    // Residue removal -------------------------------------------------------------------------------------------------

    /// Removes everything the spike installed on EVERY exit path, panic
    /// included. Leaving a synthetic resolver or a TEST-NET route behind would
    /// break every later test on the runner.
    pub struct Cleanup {
        pub store: SCDynamicStore,
    }

    impl Drop for Cleanup {
        fn drop(&mut self) {
            // Must not panic during an unwind.
            let _ = self.store.remove(CFString::new(&key()));
            let _ = run("route", &["-n", "delete", "-net", RESOLVER_NET]);
        }
    }

    // Probes ----------------------------------------------------------------------------------------------------------

    pub const CONTROL_MARKER: &[u8] = b"HOLE-868-SPIKE-CONTROL";

    /// A nonce label that cannot be in any cache anywhere, under a real
    /// delegated domain so a resolver that IS working answers NXDOMAIN promptly
    /// instead of doing something special (`.invalid`/`.local`/`.test` are
    /// short-circuited by the OS resolver and would never hit the wire).
    pub fn probe_name() -> String {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        format!("h{nanos:x}p{:x}.hole-dns-spike.example.com", std::process::id())
    }

    pub fn send_control() -> std::io::Result<()> {
        let sock = UdpSocket::bind((Ipv4Addr::UNSPECIFIED, 0))?;
        sock.send_to(CONTROL_MARKER, (RESOLVER, 53))?;
        Ok(())
    }

    /// The OS's own resolver, via `getaddrinfo(3)` — deliberately NOT a
    /// hand-rolled DNS client bound to the interface, which would prove only
    /// that the interface works.
    ///
    /// Detached, never joined: if the query does reach the black-holed
    /// resolver, `getaddrinfo` blocks retransmitting for as long as
    /// mDNSResponder wants to, and the thread dies with the process.
    pub fn spawn_os_lookup(name: String) {
        std::thread::spawn(move || {
            let outcome = (name.as_str(), 0u16).to_socket_addrs().map(|it| it.count());
            println!("[os-lookup] getaddrinfo({name}) -> {outcome:?}");
        });
    }

    pub fn budget(secs: u64) -> Instant {
        Instant::now() + Duration::from_secs(secs)
    }
}

/// SPIKE (#868). See the module docs for how to read the result.
#[cfg(target_os = "macos")]
#[skuld::test(labels = [TUN], serial = TUN)]
fn macos_dns_spike_synthetic_service_key_steers_the_os_resolver() {
    use tun::AbstractDevice;

    use spike::{
        budget, capture, diagnostics, key, key_present, nameservers, probe_name, publish, run, scutil_dns, scutil_show,
        send_control, spawn_os_lookup, store, withdraw, Cleanup, DnsConfigNotify, CONTROL_MARKER, RESOLVER,
        RESOLVER_NET, TUN_LOCAL, TUN_PEER,
    };

    let before_dns = scutil_dns();
    let before_nameservers = nameservers(&before_dns);
    println!("\n========== DIAGNOSTICS [before] ==========\n{before_dns}");
    println!("{}", run("netstat", &["-rn", "-f", "inet"]).1);
    println!("========== END DIAGNOSTICS [before] ==========\n");

    // 1. Open a real utun. The name is NOT requested: `tun` 0.8.13 asks XNU for
    //    the first free unit when `tun_name` is omitted, then reads the assigned
    //    name back. Everything downstream keys on that discovered name.
    //
    //    An empty `Configuration`: addressing and bring-up are left to
    //    `ifconfig` below, so a failure there lands in the log as the tool's own
    //    stderr rather than as an opaque ioctl error inside the crate.
    let cfg = tun::Configuration::default();
    let dev = tun::create(&cfg).expect("HARNESS: open a kernel-assigned utun");
    let tun_name = dev
        .tun_name()
        .expect("HARNESS: read back the kernel-assigned utun name");
    println!("[spike] utun opened as {tun_name}");

    // 2. Address it point-to-point and route the test resolver into it.
    let (local, peer) = (TUN_LOCAL.to_string(), TUN_PEER.to_string());
    let (ok, out) = run(
        "ifconfig",
        &[
            tun_name.as_str(),
            "inet",
            local.as_str(),
            peer.as_str(),
            "netmask",
            "255.255.255.255",
            "mtu",
            "1500",
            "up",
        ],
    );
    println!("{out}");
    assert!(
        ok,
        "HARNESS: addressing {tun_name} failed; nothing about the mechanism is being tested yet"
    );

    let (ok, out) = run(
        "route",
        &["-n", "add", "-net", RESOLVER_NET, "-interface", tun_name.as_str()],
    );
    println!("{out}");
    assert!(ok, "HARNESS: routing {RESOLVER_NET} into {tun_name} failed");

    // Everything installed from here is removed on every path, panics included.
    let cleanup = Cleanup { store: store() };

    // 3. HARNESS CONTROL, FIRST. Our own datagram to the resolver address must
    //    surface on the utun. If this fails the routing or the frame handling is
    //    wrong and the mechanism is not implicated at all.
    let mut seen = Vec::new();
    send_control().expect("HARNESS: send the control datagram to the test resolver");
    let control = capture(&dev, budget(20), &mut seen, |udp| {
        udp.dst == RESOLVER && udp.payload.windows(CONTROL_MARKER.len()).any(|w| w == CONTROL_MARKER)
    });
    println!("[spike] frames seen during control: {seen:#?}");
    diagnostics("control", &tun_name);
    assert!(
        control,
        "CONTROL FAILED — our OWN datagram to {RESOLVER} never surfaced on {tun_name}. \
         This is a harness/routing/frame-handling defect and says NOTHING about whether the \
         synthetic-service DNS mechanism works. Frames seen: {seen:#?}"
    );
    println!("[spike] CONTROL PASSED: the utun and its route carry traffic to {RESOLVER}.");

    // 4. Publish the synthetic resolver. Register for configd's change post
    //    BEFORE writing, so the settle below cannot miss the post we cause.
    let notify = DnsConfigNotify::register().expect("register for configd's dns_configuration notification");
    assert!(
        publish(&cleanup.store),
        "HARNESS: SCDynamicStoreSetValue rejected {}",
        key()
    );
    assert!(
        key_present(&cleanup.store),
        "HARNESS: the key we just set is not readable back"
    );
    println!("[spike] published {}:\n{}", key(), scutil_show(&key()));

    let merged = notify.settle(budget(30), &RESOLVER.to_string(), true);
    println!("[spike] configd merged the synthetic resolver into the DNS configuration: {merged}");
    diagnostics("published", &tun_name);

    // 5. Judge the OPERATING SYSTEM's resolver, not our own socket. A single
    //    blocking getaddrinfo retransmits on its own schedule for as long as
    //    mDNSResponder wants to, so no retry loop is needed here.
    let name = probe_name();
    println!("[spike] probing with {name}");
    spawn_os_lookup(name.clone());
    let label = name
        .split('.')
        .next()
        .expect("the probe name has a first label")
        .to_owned();

    let mut seen = Vec::new();
    let steered = capture(&dev, budget(60), &mut seen, |udp| {
        udp.dst == RESOLVER && udp.dport == 53 && udp.payload.windows(label.len()).any(|w| w == label.as_bytes())
    });
    println!("[spike] frames seen during the OS lookup: {seen:#?}");
    diagnostics("probed", &tun_name);

    // 6. Withdraw and prove the machine is back to where it started.
    assert!(
        withdraw(&cleanup.store),
        "SCDynamicStoreRemoveValue failed for {}",
        key()
    );
    assert!(!key_present(&cleanup.store), "the key is still readable after removal");
    let unmerged = notify.settle(budget(30), &RESOLVER.to_string(), false);

    let (_, out) = run("route", &["-n", "delete", "-net", RESOLVER_NET]);
    println!("{out}");

    let after_dns = scutil_dns();
    let after_nameservers = nameservers(&after_dns);
    println!("\n========== DIAGNOSTICS [after] ==========\n{after_dns}");
    println!("{}", run("netstat", &["-rn", "-f", "inet"]).1);
    println!("{}", run("route", &["-n", "get", &RESOLVER.to_string()]).1);
    println!("========== END DIAGNOSTICS [after] ==========\n");

    println!(
        "\n========== SPIKE VERDICT ==========\n\
         control passed  : true\n\
         key accepted    : true\n\
         configd merged  : {merged}\n\
         OS query steered: {steered}\n\
         removal clean   : {unmerged}\n\
         MECHANISM       : {}\n\
         ==================================\n",
        if steered { "YES" } else { "NO" }
    );

    assert!(
        unmerged,
        "REMOVAL NOT CLEAN: {RESOLVER} still appears in the DNS configuration after the key was removed \
         and confirmed absent from the store. scutil --dns:\n{after_dns}"
    );
    assert_eq!(
        before_nameservers, after_nameservers,
        "REMOVAL NOT CLEAN: the machine's resolver set changed across the spike; \
         nothing of the user's was ever captured, so nothing should have moved"
    );
    assert!(
        steered,
        "MECHANISM: NO — the control passed (so the utun and its route are sound) and configd \
         {} the synthetic resolver, but the OS's own resolver never sent the probe query for {name} \
         to {RESOLVER}. A synthetic-service supplemental DNS entry does NOT steer this macOS. \
         Frames seen on {tun_name} during the lookup: {seen:#?}",
        if merged { "DID merge" } else { "did NOT merge" }
    );
}
