//! Generate `ui/generated.ts` from Rust constants. `--check` (a prek/CI hook) fails
//! if the committed file is stale. Reads the const VALUE via the `hole-common` dep.

use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};

/// The exact contents of `ui/generated.ts`.
pub fn ui_constants_ts() -> String {
    let msg = serde_json::to_string(hole_common::protocol::NETWORK_BLOCKED_MESSAGE)
        .expect("&str always serializes to a JSON string");
    format!(
        "// @generated by `cargo xtask gen-ui-constants` — do not edit by hand.\n\
         // Source of truth: hole_common::protocol::NETWORK_BLOCKED_MESSAGE\n\
         export const NETWORK_BLOCKED_MESSAGE = {msg};\n"
    )
}

fn target(repo_root: &Path) -> PathBuf {
    repo_root.join("ui").join("generated.ts")
}

/// Write `ui/generated.ts`, or (with `check`) verify it matches and error if not.
pub fn write_or_check(repo_root: &Path, check: bool) -> Result<()> {
    let path = target(repo_root);
    let want = ui_constants_ts();
    if check {
        let have = std::fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
        if have != want {
            bail!(
                "{} is stale — run `cargo xtask gen-ui-constants` and commit",
                path.display()
            );
        }
    } else {
        std::fs::write(&path, want).with_context(|| format!("writing {}", path.display()))?;
        println!("xtask: wrote {}", path.display());
    }
    Ok(())
}
