//! Generate `ui/generated.ts` from Rust constants. `--check` (a prek/CI hook) fails
//! if the committed file is stale. Reads the const VALUE via the `hole-common` dep.

use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};

/// The Rust constants exported to TypeScript, as `(TS name, TS literal)`. Values
/// render via `serde_json`, so a value whose JSON isn't a valid TS literal (an int
/// past 2^53, or an exotic-Unicode string on a pre-ES2019 target) needs a
/// dedicated conversion first.
fn exported_constants() -> Vec<(&'static str, String)> {
    use hole_common::protocol;
    macro_rules! exported {
        ($($name:ident),+ $(,)?) => {
            vec![$( (stringify!($name), serde_json::to_string(&protocol::$name).expect("UI constant serializes to JSON")) ),+]
        };
    }
    exported!(NETWORK_BLOCKED_MESSAGE, LATENCY_VALIDATED_ON_CONNECT)
}

/// The exact contents of `ui/generated.ts`.
pub fn ui_constants_ts() -> String {
    let mut out = String::from(
        "// @generated by `cargo xtask gen-ui-constants` — do not edit by hand.\n\
         // Source of truth: constants in hole_common::protocol.\n",
    );
    for (name, literal) in exported_constants() {
        out.push_str(&format!("export const {name} = {literal};\n"));
    }
    out
}

fn target(repo_root: &Path) -> PathBuf {
    repo_root.join("ui").join("generated.ts")
}

/// Write `ui/generated.ts`, or (with `check`) verify it matches and error if not.
pub fn write_or_check(repo_root: &Path, check: bool) -> Result<()> {
    let path = target(repo_root);
    let want = ui_constants_ts();
    if check {
        let have = std::fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
        if have != want {
            bail!(
                "{} is stale — run `cargo xtask gen-ui-constants` and commit",
                path.display()
            );
        }
    } else {
        std::fs::write(&path, want).with_context(|| format!("writing {}", path.display()))?;
        println!("xtask: wrote {}", path.display());
    }
    Ok(())
}
