// @generated by `cargo xtask gen-ui-constants` — do not edit by hand.
// Source of truth: hole_common::protocol::NETWORK_BLOCKED_MESSAGE
export const NETWORK_BLOCKED_MESSAGE = "The network is blocking the connection to this server — the handshake was reset or got no response. This usually means a firewall or censorship; try a different server.";
