"""Build + validation tests for hole.wxs.

Builds an MSI with dummy binaries, then validates it via ICE checks and
table inspection. Windows-only, requires WiX toolchain.
"""

import platform
import shutil
import struct
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

import msi_installer
from conftest import NS, WXS_PATH

pytestmark = [
    pytest.mark.skipif(platform.system() != "Windows", reason="Windows-only (needs WiX + msiexec)"),
    pytest.mark.wix,
]

# Fixtures =============================================================================================================


@pytest.fixture(scope="session")
def staged_dir(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Create a staging directory with non-zero dummy binaries.

    Non-zero so the embedded cabinet actually contains data and the
    relocated-extract test (#357) has files to find post-extraction.
    """
    d = tmp_path_factory.mktemp("stage")
    # hole.pdb shipped alongside hole.exe for symbolicated panic
    # backtraces — see bindreams/hole#393. Mirrors the bindir layout
    # produced by `cargo xtask stage`.
    for name in ("hole.exe", "hole.pdb", "ex-ray.exe", "wintun.dll", "NOTICES.md"):
        (d / name).write_bytes(b"x" * 1024)
    return d


def _build_minimal_ico() -> bytes:
    """Build a 1x1 32-bpp ICO blob (70 bytes).

    Real production builds use .cache/icons/icon.ico (3 sizes,
    generated by crates/hole/build.rs::render_ico). For tests we
    construct an inline ICO so the suite stays self-contained — no
    dependency on a prior `cargo build` having populated the cache.
    """
    # ICONDIR: reserved=0, type=1 (icon), count=1
    icondir = struct.pack("<HHH", 0, 1, 1)
    # ICONDIRENTRY: 1x1, no palette, 32bpp, BITMAPINFOHEADER + 1 pixel + AND mask
    image_size = 40 + 4 + 4  # BITMAPINFOHEADER(40) + pixel(4) + AND mask(4)
    image_offset = 22  # icondir(6) + direntry(16)
    direntry = struct.pack("<BBBBHHII", 1, 1, 0, 0, 1, 32, image_size, image_offset)
    # BITMAPINFOHEADER: size=40, width=1, height=2 (XOR+AND), planes=1, bpp=32, no compression
    bih = struct.pack("<IIIHHIIIIII", 40, 1, 2, 1, 32, 0, 0, 0, 0, 0, 0)
    # One BGRA pixel (opaque black)
    pixel = b"\x00\x00\x00\xff"
    # 4-byte AND mask (1x1 padded to DWORD)
    and_mask = b"\x00\x00\x00\x00"
    return icondir + direntry + bih + pixel + and_mask


@pytest.fixture(scope="session")
def icon_dir(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Create a directory containing a minimal valid ICO file.

    hole.wxs references `!(bindpath.IconDir)\\icon.ico`. The real
    production icon lives at .cache/icons/icon.ico; tests write a
    70-byte 1x1 ICO so they don't depend on a prior cargo build.
    """
    d = tmp_path_factory.mktemp("icons")
    (d / "icon.ico").write_bytes(_build_minimal_ico())
    return d


@pytest.fixture(scope="session")
def stub_license_dir(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Minimal RTF for the WixUI License dialog. The real license.rtf is not under test."""
    d = tmp_path_factory.mktemp("license")
    (d / "license.rtf").write_bytes(b"{\\rtf1\\ansi Test license\\par}")
    return d


@pytest.fixture(scope="session")
def built_msi(
    wix_exe: Path,
    staged_dir: Path,
    icon_dir: Path,
    stub_license_dir: Path,
    tmp_path_factory: pytest.TempPathFactory,
) -> Path:
    """Build an MSI from hole.wxs with dummy binaries, icon, and stub license."""
    out_dir = tmp_path_factory.mktemp("msi")
    msi_path = out_dir / "hole.msi"
    result = subprocess.run(
        [
            str(wix_exe),
            "build",
            str(WXS_PATH),
            "-arch",
            "x64",
            "-ext",
            str(msi_installer.ui_extension_path(wix_exe)),
            "-bindpath",
            f"BinDir={staged_dir}",
            "-bindpath",
            f"IconDir={icon_dir}",
            "-bindpath",
            f"LicenseDir={stub_license_dir}",
            "-d",
            "ProductVersion=1.0.0",
            "-o",
            str(msi_path),
        ],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"wix build failed (exit {result.returncode}):\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    return msi_path


@pytest.fixture(scope="session")
def decompiled_tree(wix_exe: Path, built_msi: Path, tmp_path_factory: pytest.TempPathFactory) -> ET.ElementTree:
    """Decompile the built MSI back to XML for table inspection."""
    out_dir = tmp_path_factory.mktemp("decompiled")
    wxs_out = out_dir / "decompiled.wxs"
    result = subprocess.run(
        [str(wix_exe), "msi", "decompile", str(built_msi), "-o",
         str(wxs_out)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (f"wix msi decompile failed (exit {result.returncode}):\n{result.stderr}")
    return ET.parse(wxs_out)


# Build tests ==========================================================================================================


def test_wix_build_succeeds(built_msi: Path) -> None:
    """wix build should exit 0 and produce an MSI file."""
    assert built_msi.exists()
    assert built_msi.stat().st_size > 0


def test_ice_validation_passes(wix_exe: Path, built_msi: Path) -> None:
    """wix msi validate should pass all ICE checks."""
    result = subprocess.run(
        [str(wix_exe), "msi", "validate", str(built_msi)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"ICE validation failed (exit {result.returncode}):\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )


# Sequence number tests ================================================================================================


def _get_decompiled_sequence_map(tree: ET.ElementTree) -> dict[str, dict]:
    """Extract InstallExecuteSequence entries from decompiled XML.

    Returns {action_name: {"before": ..., "after": ..., "condition": ...}}.
    """
    pkg = tree.getroot().find("wix:Package", NS)
    assert pkg is not None
    seq = pkg.find("wix:InstallExecuteSequence", NS)
    assert seq is not None, "InstallExecuteSequence not found in decompiled MSI"

    entries = {}
    for custom in seq.findall("wix:Custom", NS):
        action = custom.get("Action", "")
        entries[action] = {
            "before": custom.get("Before"),
            "after": custom.get("After"),
            "condition": custom.get("Condition", ""),
        }
    return entries


def test_sequence_install_order(decompiled_tree: ET.ElementTree) -> None:
    """Install CAs must be ordered: InstallFiles < BridgeInstall < PathAdd."""
    entries = _get_decompiled_sequence_map(decompiled_tree)

    assert "BridgeInstall" in entries, "BridgeInstall not found in InstallExecuteSequence"
    assert "PathAdd" in entries, "PathAdd not found in InstallExecuteSequence"

    assert entries["BridgeInstall"]["after"] == "InstallFiles", (
        f"BridgeInstall should be After='InstallFiles', "
        f"got After='{entries['BridgeInstall']['after']}'"
    )
    assert entries["PathAdd"]["after"] == "BridgeInstall", (
        f"PathAdd should be After='BridgeInstall', "
        f"got After='{entries['PathAdd']['after']}'"
    )


def test_sequence_uninstall_order(decompiled_tree: ET.ElementTree) -> None:
    """Uninstall CAs must be ordered: PathRemove < BridgeUninstall < RemoveFiles."""
    entries = _get_decompiled_sequence_map(decompiled_tree)

    assert "BridgeUninstall" in entries, "BridgeUninstall not found in InstallExecuteSequence"
    assert "PathRemove" in entries, "PathRemove not found in InstallExecuteSequence"

    assert entries["BridgeUninstall"]["before"] == "RemoveFiles", (
        f"BridgeUninstall should be Before='RemoveFiles', "
        f"got Before='{entries['BridgeUninstall']['before']}'"
    )
    assert entries["PathRemove"]["before"] == "BridgeUninstall", (
        f"PathRemove should be Before='BridgeUninstall', "
        f"got Before='{entries['PathRemove']['before']}'"
    )


# Component bitness tests ==============================================================================================


def test_components_are_64bit(decompiled_tree: ET.ElementTree) -> None:
    """All components must target 64-bit (not 'always32').

    A 32-bit MSI installs to Program Files (x86) instead of Program Files,
    which is incorrect for x64 binaries.
    """
    pkg = decompiled_tree.getroot().find("wix:Package", NS)
    assert pkg is not None

    for comp in pkg.iter(f"{{{NS['wix']}}}Component"):
        comp_id = comp.get("Id", "<anonymous>")
        bitness = comp.get("Bitness", "")
        assert bitness != "always32", (
            f"Component '{comp_id}' has Bitness='always32' (32-bit). "
            "Pass '-arch x64' to 'wix build' to build a 64-bit MSI."
        )


# ARP icon tests =======================================================================================================


def test_arp_product_icon_in_msi(decompiled_tree: ET.ElementTree) -> None:
    """The built MSI must carry ARPPRODUCTICON pointing at a declared Icon.

    MSI-side mirror of test_hole_wxs.py::test_arp_product_icon_defined.
    Without ARPPRODUCTICON, Windows shows a generic installer icon in
    Add/Remove Programs (#359).
    """
    pkg = decompiled_tree.getroot().find("wix:Package", NS)
    assert pkg is not None

    icon_ids = {icon.get("Id") for icon in pkg.iter(f"{{{NS['wix']}}}Icon")}
    assert icon_ids, "Decompiled MSI has no <Icon> entries — ARPPRODUCTICON has nothing to reference"

    arp_property = None
    for prop in pkg.iter(f"{{{NS['wix']}}}Property"):
        if prop.get("Id") == "ARPPRODUCTICON":
            arp_property = prop
            break
    assert arp_property is not None, (
        "Decompiled MSI has no ARPPRODUCTICON property. ARP entry will "
        "show a generic installer icon (#359)."
    )

    value = arp_property.get("Value", "")
    assert value in icon_ids, (
        f"ARPPRODUCTICON='{value}' does not match any Icon Id in the MSI. "
        f"Icon Ids: {sorted(icon_ids)}"
    )


# Cabinet embedding tests ==============================================================================================


def test_decompiled_msi_cab_is_embedded(decompiled_tree: ET.ElementTree) -> None:
    """The built MSI's Media table must declare embedded cabinets.

    `wix msi decompile` translates the on-disk Cabinet='#name.cab' embedded
    marker back to source form: it strips the '#' and emits EmbedCab='yes'
    on each <Media>. Absence of EmbedCab='yes' on the decompiled XML means
    the MSI ships external cabs and breaks for end users (#357 — v0.1.0).
    """
    pkg = decompiled_tree.getroot().find("wix:Package", NS)
    assert pkg is not None
    media_elements = list(pkg.iter(f"{{{NS['wix']}}}Media"))
    assert media_elements, "Decompiled MSI has no <Media> element"
    for media in media_elements:
        embed = media.get("EmbedCab", "")
        assert embed == "yes", (
            f"<Media Id='{media.get('Id')}' Cabinet='{media.get('Cabinet')}' "
            f"EmbedCab='{embed}'> declares an EXTERNAL cabinet. "
            "Set <MediaTemplate EmbedCab='yes'> in hole.wxs."
        )


def test_built_msi_has_no_external_cab(built_msi: Path) -> None:
    """No .cab file should sit next to the built .msi.

    External cabs land in the same directory as the .msi with a name like
    'cab1.cab'. End users who download only the .msi then get 'Source file
    not found: cab1.cab' at install time (#357 — v0.1.0).
    """
    siblings = list(built_msi.parent.glob("*.cab"))
    assert not siblings, (
        f"Found external cabinet(s) next to the built MSI: {siblings}. "
        "The MSI must be self-contained (<MediaTemplate EmbedCab='yes'>)."
    )


def test_msi_admin_extract_works_when_separated_from_build_dir(
    built_msi: Path,
    tmp_path_factory: pytest.TempPathFactory,
) -> None:
    """Simulate the end-user 'download MSI alone and run it' flow.

    Copy the .msi alone to a fresh directory (no cab siblings) and run
    `msiexec /a` — administrative install, read-only extract, no admin
    rights, no system mutation. External-cab MSIs fail here with the same
    'cab1.cab not found' error that broke v0.1.0 (#357).
    """
    relocated_dir = tmp_path_factory.mktemp("relocated")
    relocated = Path(shutil.copy(built_msi, relocated_dir / "hole.msi"))
    extract_dir = tmp_path_factory.mktemp("extract")
    abs_target = str(extract_dir.resolve())

    # Trailing backslash on TARGETDIR is required by msiexec.
    result = subprocess.run(
        ["msiexec", "/a", str(relocated.resolve()), f"TARGETDIR={abs_target}\\", "/qn"],
        capture_output=True,
        text=True,
        timeout=120,
    )
    assert result.returncode == 0, (
        f"msiexec /a failed (exit {result.returncode}) on a relocated MSI — "
        f"the same code path that failed for v0.1.0 end users.\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )

    payload_files = {"hole.exe", "hole.pdb", "ex-ray.exe", "wintun.dll", "NOTICES.md"}
    extracted = {p.name for p in extract_dir.rglob("*") if p.is_file() and p.name in payload_files}
    assert extracted == payload_files, (f"MSI extracted but expected payload missing: got {extracted}")


# UI property + dialog tests ===========================================================================================


def _decompiled_package(tree: ET.ElementTree) -> ET.Element:
    pkg = tree.getroot().find("wix:Package", NS)
    assert pkg is not None
    return pkg


def _find_property(pkg: ET.Element, prop_id: str) -> ET.Element | None:
    for prop in pkg.iter(f"{{{NS['wix']}}}Property"):
        if prop.get("Id") == prop_id:
            return prop
    return None


def test_decompiled_has_install_start_menu_default(decompiled_tree: ET.ElementTree) -> None:
    pkg = _decompiled_package(decompiled_tree)
    prop = _find_property(pkg, "INSTALL_START_MENU")
    assert prop is not None, "INSTALL_START_MENU property missing from built MSI"
    assert prop.get("Value") == "1", (
        f"INSTALL_START_MENU default must be '1' (silent-upgrade safety); "
        f"got '{prop.get('Value')}'"
    )


def test_decompiled_has_install_desktop_icon_default(decompiled_tree: ET.ElementTree) -> None:
    pkg = _decompiled_package(decompiled_tree)
    prop = _find_property(pkg, "INSTALL_DESKTOP_ICON")
    assert prop is not None, "INSTALL_DESKTOP_ICON property missing from built MSI"
    assert prop.get("Value") == "0", (
        f"INSTALL_DESKTOP_ICON default must be '0' (silent-upgrade safety); "
        f"got '{prop.get('Value')}'"
    )


def test_decompiled_has_shortcutsdlg(decompiled_tree: ET.ElementTree) -> None:
    pkg = _decompiled_package(decompiled_tree)
    for dlg in pkg.iter(f"{{{NS['wix']}}}Dialog"):
        if dlg.get("Id") == "ShortcutsDlg":
            return
    raise AssertionError("Dialog 'ShortcutsDlg' missing from built MSI")


# UI override-wins tests ===============================================================================================
#
# `wix msi decompile` lowers MSI ControlEvent rows to nested <Publish>
# children under each Control. The order in which rows fire — the MSI Order
# column ascending — is preserved as XML document order. For NewDialog, the
# LAST row with a true condition wins (each fired Publish sets the new
# dialog, last writer wins). So "our override beats upstream" is structurally
# equivalent to "the last NewDialog <Publish> under (Dialog/Control) has our
# target as Value".


def _new_dialog_targets(pkg: ET.Element, dialog_id: str, control_id: str, condition: str | None = None) -> list[str]:
    """Return Value of every NewDialog <Publish> under (dialog_id/control_id), in document order.

    If `condition` is set, only rows whose Condition matches are returned.
    """
    targets: list[str] = []
    for dlg in pkg.iter(f"{{{NS['wix']}}}Dialog"):
        if dlg.get("Id") != dialog_id:
            continue
        for ctrl in dlg.iter(f"{{{NS['wix']}}}Control"):
            if ctrl.get("Id") != control_id:
                continue
            for pub in ctrl.iter(f"{{{NS['wix']}}}Publish"):
                if pub.get("Event") != "NewDialog":
                    continue
                if condition is not None and pub.get("Condition") != condition:
                    continue
                targets.append(pub.get("Value", ""))
    return targets


def test_installdirdlg_next_override_wins(decompiled_tree: ET.ElementTree) -> None:
    """The last NewDialog row for (InstallDirDlg, Next) must target ShortcutsDlg.

    Load-bearing: if upstream's row to VerifyReadyDlg fires last, the user
    skips ShortcutsDlg entirely. This is the structural check that our
    Order=5 override actually wins at MSI runtime.
    """
    pkg = _decompiled_package(decompiled_tree)
    targets = _new_dialog_targets(pkg, "InstallDirDlg", "Next")
    assert targets, "No NewDialog Publish rows for (InstallDirDlg, Next) in built MSI"
    assert targets[-1] == "ShortcutsDlg", (
        f"Last NewDialog row for (InstallDirDlg, Next) is '{targets[-1]}', not 'ShortcutsDlg'. "
        f"Full sequence (document order = MSI Order asc): {targets}. "
        "MSI runtime fires rows in Order asc and the last true condition wins; "
        "if our override doesn't appear last, ShortcutsDlg will be skipped."
    )


# Launch-condition tests ===============================================================================================
#
# Source-side mirror lives in test_hole_wxs.py::test_launch_condition_requires_build_19041.
# This test guards against the gate being silently dropped during the
# WiX compile → MSI → decompile round-trip (e.g. a WiX schema migration
# that changes how LaunchCondition is encoded).


def test_decompiled_has_win10_launch_condition(decompiled_tree: ET.ElementTree) -> None:
    """The built MSI must carry a LaunchCondition gating install on build >= 19041.

    `wix msi decompile` lowers a MSI LaunchCondition table row to either
    a `<Launch>` element (WiX v4+ schema) or a legacy
    `<Condition Message="...">CONDITION_TEXT</Condition>` form. Accept
    either shape; assert the condition text mentions WIN10BUILD and
    19041. See bindreams/hole#397.
    """
    pkg = _decompiled_package(decompiled_tree)

    found_conditions: list[str] = []
    for el in pkg.iter(f"{{{NS['wix']}}}Launch"):
        cond = el.get("Condition") or ""
        if "WIN10BUILD" in cond:
            found_conditions.append(cond)
    for el in pkg.iter(f"{{{NS['wix']}}}Condition"):
        # Legacy form: condition text is the element's .text, not a
        # Condition= attribute. Only Conditions carrying a Message= are
        # LaunchConditions (others gate components/features).
        if el.get("Message") and el.text and "WIN10BUILD" in el.text:
            found_conditions.append(el.text)

    assert found_conditions, (
        "Decompiled MSI has no LaunchCondition referencing WIN10BUILD. The "
        "#397 Windows-version gate is missing from the built MSI."
    )
    assert any(
        "19041" in c for c in found_conditions
    ), (f"LaunchCondition(s) found referencing WIN10BUILD but none gate on 19041. "
        f"Conditions: {found_conditions}")


def test_decompiled_has_win10build_property(decompiled_tree: ET.ElementTree) -> None:
    """The built MSI must declare a WIN10BUILD property backed by a RegistrySearch.

    Without the property, the launch condition's WIN10BUILD reference
    evaluates to empty and the gate becomes vacuous.
    """
    pkg = _decompiled_package(decompiled_tree)
    prop = _find_property(pkg, "WIN10BUILD")
    assert prop is not None, "WIN10BUILD property missing from built MSI"

    search = prop.find(f"{{{NS['wix']}}}RegistrySearch")
    assert search is not None, (
        "WIN10BUILD property has no <RegistrySearch> child in the built MSI — "
        "the gate has no value to evaluate against."
    )
    assert search.get("Name") == "CurrentBuildNumber", (
        f"WIN10BUILD RegistrySearch must read CurrentBuildNumber, "
        f"got Name='{search.get('Name')}'."
    )


def test_verifyreadydlg_back_override_wins(decompiled_tree: ET.ElementTree) -> None:
    """The last (NOT Installed) NewDialog row for (VerifyReadyDlg, Back) must target ShortcutsDlg.

    Load-bearing: this is what makes the Back button on VerifyReadyDlg lead
    back to ShortcutsDlg instead of skipping it.
    """
    pkg = _decompiled_package(decompiled_tree)
    targets = _new_dialog_targets(pkg, "VerifyReadyDlg", "Back", condition="NOT Installed")
    assert targets, (
        "No NewDialog Publish rows with Condition='NOT Installed' for "
        "(VerifyReadyDlg, Back) in built MSI"
    )
    assert targets[-1] == "ShortcutsDlg", (
        f"Last NewDialog row (Condition='NOT Installed') for (VerifyReadyDlg, Back) is "
        f"'{targets[-1]}', not 'ShortcutsDlg'. Full sequence: {targets}."
    )
